### ISSUE TITLE
Include SVG File

### ISSUE THREAD

**Issue by tomasdelvechio** [Popotojs/popotojs#2]
I've used popotojs and works fine. But I've problem.

The Designer send me svg files to use in the app, but popotojs only accept svg paths object (See the example "US regions"). I spend a lot of time "translated" the file to paths in a object. 

I looking for a method or function to "render" the svg object or include file path. 

Is there something like this?

**Comment by Popotojs** [comment]
If you want to display svg image files you can simply display them like any other types using the IMAGE node display type using a config like this:

        "getDisplayType": function (node) {
            return popoto.provider.NodeDisplayTypes.IMAGE;
        },
        "getImagePath": function (node) {
                return "your-svg-file.svg";
        },

**Comment by tomasdelvechio** [comment]
That works fine! Thanks.
