### ISSUE TITLE
Toolbar icons

### ISSUE THREAD

**Issue by tomasdelvechio** [Popotojs/popotojs#3]
I'm adding icons to the toolbar in a project. I found a CSS property content, adding "\00f065" to span, show the fullscreen icon, for example.

There are a complete list of these icons? They arent Awesome icons.

Thanks.

**Comment by Popotojs** [comment]
They aren't full Font Awesome icons but only a small subset to be as small as possible.
These icons are defined in the Popoto font files (in folder css/font) and you can see a complete list here:
http://www.popotojs.com/css/font-icon-list.html

Note that you can use any other font icons you want in your project, you just have to add a reference to the additional fonts (like Font Awsome) and use it to display icons.

**Comment by tomasdelvechio** [comment]
Thanks for the list
