### ISSUE TITLE
Regenerate entire graph from JSON

### ISSUE THREAD

**Issue by tomasdelvechio** [Popotojs/popotojs#4]
In my project, I save the object `popoto.graph.force.nodes()` and `popoto.graph.force.links()`. I generate a JSON string, and save in database of my app. After, the users load the saved graph for add new changes.

I regenerate the Graph with this code:

```
popoto.graph.force.nodes(nodes);
popoto.graph.force.links(links);
popoto.graph.hasGraphChanged = true;
popoto.result.hasChanged = true;
popoto.update();
```

nodes and links vars contain a javascript object compatible with force element.

After the update function execution, popoto show the links and nodes, but the nodes there are separated of the links (source and target of the links there aren't "linking" to the nodes. But this nodes there are rendered, but no link pointing to them).

Something I forgive to full regenerate the graph?

**Comment by Popotojs** [comment]
To save and load graph you can use the save feature available in code.
Would it work for you or do you need additional features?

To use it you can activate the option in toolbar like this:

    /**
     * Add save tool in graph, by default this parameter is set to false and the save tool icon is hidden.
     */
    popoto.tools.SAVE_GRAPH = true;

Then add a listener to this event to store the json in your database like this:

    /**
     * Listener to used to get current graph context on save icon click.
     *
     * "graph" parameter contains the current graph that can be saved in your application and restored when needed.
     */
    popoto.graph.onSave(function (graph) {
        // Save graph in your database
    });

To load a saved graph you can do this:

    function loadGraph(graph) {
        popoto.graph.setDefaultGraph(graph);
        popoto.tools.reset();
    }

Or start popoto on a saved graph

    popoto.start(savedGraph);


See a full example here, you can directly look in the page source code for details:
http://www.popotojs.com/live/save/index.html
